import deal1 from "@/assets/cb_deals/deal1.webp";
import deal2 from "@/assets/cb_deals/deal2.webp";
import deal3 from "@/assets/cb_deals/deal3.webp";
import deal4 from "@/assets/cb_deals/deal4.webp";

export const CASHBACK_DEALS = [
  {
    id: 1,
    slug: "amazon-cashback",
    brand: "Amazon",
    cashback: "Up to 8% Cashback",
    description: "Shop electronics, fashion & more with guaranteed cashback on every order.",
    href: "/deals/amazon-cashback",
    image: deal1,
    affiliateLink: "https://www.amazon.in",
    steps: [
      "Click 'Shop & Earn Cashback' — you'll be redirected to Amazon.",
      "Log in to your account or create a new one.",
      "Browse and add any product to your cart.",
      "Complete checkout and make your payment.",
      "Cashback will be tracked automatically within 24–48 hours.",
    ],
  },
  {
    id: 2,
    slug: "flipkart-cashback",
    brand: "Flipkart",
    cashback: "Up to 10% Cashback",
    description: "Exclusive cashback on mobiles, appliances and daily essentials.",
    href: "/deals/flipkart-cashback",
    image: deal2,
    affiliateLink: "https://www.flipkart.com",
    steps: [
      "Click 'Shop & Earn Cashback' to go to Flipkart.",
      "Log in or create a new account.",
      "Choose from mobiles, appliances or any product.",
      "Pay via UPI, card or EMI.",
      "Cashback will be tracked within 48 hours.",
    ],
  },
  {
    id: 3,
    slug: "myntra-cashback",
    brand: "Myntra",
    cashback: "Up to 12% Cashback",
    description: "Earn cashback on top fashion brands, footwear and accessories.",
    href: "/deals/myntra-cashback",
    image: deal3,
    affiliateLink: "https://www.myntra.com",
    steps: [
      "Click 'Shop & Earn Cashback' — you'll be redirected to Myntra.",
      "Browse fashion brands or search for your favourite.",
      "Select your size and add to cart.",
      "Complete checkout using any payment method.",
      "Up to 12% cashback will be tracked after order delivery.",
    ],
  },
  {
    id: 4,
    slug: "nykaa-cashback",
    brand: "Nykaa",
    cashback: "Up to 15% Cashback",
    description: "Beauty, skincare and wellness products with high cashback rewards.",
    href: "/deals/nykaa-cashback",
    image: deal4,
    affiliateLink: "https://www.nykaa.com",
    steps: [
      "Click the button and get redirected to Nykaa.",
      "Browse beauty, skincare or wellness products.",
      "Add your chosen products to cart.",
      "Complete your checkout.",
      "15% cashback will be tracked within 72 hours.",
    ],
  },
  {
    id: 5,
    slug: "ajio-cashback",
    brand: "Ajio",
    cashback: "Up to 14% Cashback",
    description: "Premium fashion labels and lifestyle brands with great savings.",
    href: "/deals/ajio-cashback",
    image: deal1,
    affiliateLink: "https://www.ajio.com",
    steps: [
      "Click 'Shop & Earn Cashback' to visit Ajio.",
      "Explore premium brands and lifestyle collections.",
      "Add your selected items to cart.",
      "Complete your payment.",
      "Cashback will be tracked within 48–72 hours.",
    ],
  },
  {
    id: 6,
    slug: "zomato-cashback",
    brand: "Zomato",
    cashback: "Up to 20% Cashback",
    description: "Order food from your favourite restaurants and earn cashback.",
    href: "/deals/zomato-cashback",
    image: deal2,
    affiliateLink: "https://www.zomato.com",
    steps: [
      "Click the button to go to Zomato app or website.",
      "Choose your favourite restaurant.",
      "Place your food order.",
      "Pay online — cashback is not applicable on cash on delivery.",
      "Up to 20% cashback will be tracked after order completion.",
    ],
  },
];
