import { Shirt, Smartphone, Sparkles, Dumbbell } from "lucide-react";
import banner1 from "@/assets/banner/banner1.png";
import banner2 from "@/assets/banner/banner2.png";
import banner3 from "@/assets/banner/banner3.png";

export const DEALS_OF_THE_DAY = [
  {
    id: 1,
    slug: "nike-air-max-running-shoes",
    brand: "Nike",
    title: "Air Max Running Shoes",
    description:
      "Nike Air Max features cutting-edge Air cushioning technology that delivers maximum comfort with every step. Lightweight mesh upper keeps your feet breathable and stylish — perfect from the gym to casual outings.",
    originalPrice: 8999,
    discountedPrice: 4499,
    discount: 50,
    tag: "Hot Deal",
    icon: Shirt,
    gradientFrom: "from-rose-50",
    gradientTo: "to-pink-100",
    iconColor: "text-rose-300",
    badgeColor: "bg-rose-500",
    accentColor: "text-rose-500",
    image: banner1,
    rating: 4.5,
    grabbed: 234,
    href: "/deals/nike-air-max-running-shoes",
    affiliateLink: "https://www.nike.com",
    steps: [
      "Click the 'Shop & Earn Cashback' button — you'll be redirected to Nike's official site.",
      "Select your preferred size and color.",
      "Add the item to your cart and proceed to checkout.",
      "Apply any available coupon code at payment.",
      "Complete your order — cashback will be tracked automatically.",
    ],
  },
  {
    id: 2,
    slug: "samsung-galaxy-buds-pro",
    brand: "Samsung",
    title: "Galaxy Buds Pro — Wireless",
    description:
      "Samsung Galaxy Buds Pro feature Intelligent Active Noise Cancellation that blocks up to 99% of ambient noise. Enjoy 360 Audio and Hi-Fi sound for an immersive listening experience. IPX7 water resistance keeps them safe at the gym or in the rain.",
    originalPrice: 12999,
    discountedPrice: 6999,
    discount: 46,
    tag: "Limited",
    icon: Smartphone,
    gradientFrom: "from-blue-50",
    gradientTo: "to-indigo-100",
    iconColor: "text-blue-300",
    badgeColor: "bg-blue-500",
    accentColor: "text-blue-500",
    image: banner2,
    rating: 4.3,
    grabbed: 189,
    href: "/deals/samsung-galaxy-buds-pro",
    affiliateLink: "https://www.samsung.com/in",
    steps: [
      "Click 'Shop & Earn Cashback' — you'll be taken to Samsung's official store.",
      "Choose your preferred color variant (Black / White / Violet).",
      "Add to cart and log in if you haven't already.",
      "Check available bank offers for an extra 10% off.",
      "Place your order — delivery within 2–3 business days.",
    ],
  },
  {
    id: 3,
    slug: "mamaearth-vitamin-c-skincare-combo",
    brand: "Mamaearth",
    title: "Vitamin C Skincare Combo",
    description:
      "Mamaearth Vitamin C Combo includes a face wash, serum and moisturizer that work together to brighten skin, reduce dark spots and deliver a natural glow. Made with 100% natural, dermatologically tested, toxin-free ingredients.",
    originalPrice: 1499,
    discountedPrice: 749,
    discount: 50,
    tag: "Best Seller",
    icon: Sparkles,
    gradientFrom: "from-purple-50",
    gradientTo: "to-violet-100",
    iconColor: "text-purple-300",
    badgeColor: "bg-purple-500",
    accentColor: "text-purple-500",
    image: banner3,
    rating: 4.7,
    grabbed: 412,
    href: "/deals/mamaearth-vitamin-c-skincare-combo",
    affiliateLink: "https://www.mamaearth.in",
    steps: [
      "Click 'Shop & Earn Cashback' to visit the Mamaearth store.",
      "Select the combo pack (choose quantity as needed).",
      "Try coupon code 'MAMA10' at checkout for an extra discount.",
      "Choose Cash on Delivery or online payment — both available.",
      "Order delivered in 5–7 days with free samples included.",
    ],
  },
  {
    id: 4,
    slug: "decathlon-yoga-mat-resistance-kit",
    brand: "Decathlon",
    title: "Yoga Mat & Resistance Kit",
    description:
      "Decathlon's combo is perfect for both gym and home workouts. Includes an anti-slip yoga mat with a carrying strap and 5 resistance band levels — suitable for beginners to advanced users. Eco-friendly, durable and compact.",
    originalPrice: 2499,
    discountedPrice: 999,
    discount: 60,
    tag: "Today Only",
    icon: Dumbbell,
    gradientFrom: "from-teal-50",
    gradientTo: "to-emerald-100",
    iconColor: "text-teal-300",
    badgeColor: "bg-teal-500",
    accentColor: "text-teal-500",
    image: banner1,
    rating: 4.2,
    grabbed: 97,
    href: "/deals/decathlon-yoga-mat-resistance-kit",
    affiliateLink: "https://www.decathlon.in",
    steps: [
      "Click 'Shop & Earn Cashback' — you'll be redirected to Decathlon's website.",
      "Select your preferred kit color and size.",
      "Place your order as a guest or with your account.",
      "Choose home delivery or pick up from your nearest Decathlon store.",
      "Deal valid today only — grab it before it expires!",
    ],
  },
];
