import amazon from "@/assets/store_icon/amazon.png";
import flipkart from "@/assets/store_icon/flipkart.png";
import myntra from "@/assets/store_icon/myntra.png";
import nykaa from "@/assets/store_icon/naykaa.webp";
import ajio from "@/assets/store_icon/ajio.png";
import zomato from "@/assets/store_icon/zomato.png";
import swiggy from "@/assets/store_icon/swiggy.png";
import samsung from "@/assets/store_icon/samsung.png";

export const TRENDING_COUPONS = [
  {
    id: 1,
    store: "Amazon",
    storeIcon: amazon,
    code: "AMZN50OFF",
    slug: "amazon-flat-50-off",
    title: "Flat 50% Off Sitewide",
    description: "Get 50% off on electronics, fashion and more. Valid for new users only. Minimum order ₹499.",
    href: "/stores?brand=amazon",
    affiliateLink: "https://www.amazon.in",
    steps: [
      "Create or log in to your Amazon.in account.",
      "Add your preferred products to the cart.",
      "Go to checkout and click 'Apply Coupon Code'.",
      "Enter code 'AMZN50OFF' and click Apply.",
      "The discount will be applied automatically — enjoy!",
    ],
  },
  {
    id: 2,
    store: "Flipkart",
    storeIcon: flipkart,
    code: "FKBIG10",
    slug: "flipkart-cashback-10",
    title: "Up to 10% Cashback",
    description: "Use this code on mobiles & appliances to earn instant cashback. Valid on select products.",
    href: "/stores?brand=flipkart",
    affiliateLink: "https://www.flipkart.com",
    steps: [
      "Log in to your Flipkart account.",
      "Go to the Mobiles or Appliances section.",
      "Select a product and add it to your cart.",
      "Apply coupon code 'FKBIG10' at payment.",
      "Cashback will be credited to your wallet within 24 hours.",
    ],
  },
  {
    id: 3,
    store: "Myntra",
    storeIcon: myntra,
    code: "MYNTRA12",
    slug: "myntra-extra-12-off",
    title: "Extra 12% Off on Fashion",
    description: "Shop from top fashion labels and save big with this exclusive code. Valid on MRP items.",
    href: "/stores?brand=myntra",
    affiliateLink: "https://www.myntra.com",
    steps: [
      "Log in to Myntra app or website.",
      "Browse your favourite fashion items.",
      "Add items worth ₹999 or more to your cart.",
      "Apply code 'MYNTRA12' at checkout.",
      "12% extra discount will be applied instantly!",
    ],
  },
  {
    id: 4,
    store: "Nykaa",
    storeIcon: nykaa,
    code: "NYKAA15",
    slug: "nykaa-15-off-beauty",
    title: "15% Off on Beauty",
    description: "Skincare, makeup and wellness — grab extra savings with this coupon. Min order ₹799.",
    href: "/stores?brand=nykaa",
    affiliateLink: "https://www.nykaa.com",
    steps: [
      "Visit Nykaa.com or the app and log in.",
      "Choose skincare, makeup or wellness products.",
      "Add items worth ₹799 or more to your cart.",
      "Apply promo code 'NYKAA15' at checkout.",
      "15% instant discount will be applied to your bill!",
    ],
  },
  {
    id: 5,
    store: "Ajio",
    storeIcon: ajio,
    code: "AJIO14",
    slug: "ajio-14-off-premium",
    title: "14% Off on Premium Brands",
    description: "Exclusive discount on lifestyle and premium fashion collections. First purchase offer.",
    href: "/stores?brand=ajio",
    affiliateLink: "https://www.ajio.com",
    steps: [
      "Visit Ajio.com and create or log in to your account.",
      "Browse the Premium Brands section and make your selection.",
      "Add one or more items to your cart.",
      "Paste code 'AJIO14' at checkout.",
      "14% off will be deducted from your bill instantly!",
    ],
  },
  {
    id: 6,
    store: "Zomato",
    storeIcon: zomato,
    code: "ZOM20CB",
    slug: "zomato-20-cashback",
    title: "20% Cashback on Orders",
    description: "Order your favourite food and earn cashback on every delivery. Valid on online payment.",
    href: "/stores?brand=zomato",
    affiliateLink: "https://www.zomato.com",
    steps: [
      "Open the Zomato app and set your location.",
      "Choose your favourite restaurant.",
      "Place an order of minimum ₹299.",
      "Apply code 'ZOM20CB' at the payment screen.",
      "20% cashback will be credited to Zomato Money!",
    ],
  },
  {
    id: 7,
    store: "Swiggy",
    storeIcon: swiggy,
    code: "SWGY20",
    slug: "swiggy-20-off-first-order",
    title: "20% Off First Order",
    description: "New to Swiggy? Use this code and save on your very first order. Max discount ₹100.",
    href: "/stores?brand=swiggy",
    affiliateLink: "https://www.swiggy.com",
    steps: [
      "Download the Swiggy app and create a new account.",
      "Choose any restaurant in your area.",
      "Select your food items and add to cart.",
      "Apply promo code 'SWGY20' at checkout.",
      "20% off will be applied to your very first order!",
    ],
  },
  {
    id: 8,
    store: "Samsung",
    storeIcon: samsung,
    code: "SAM6BACK",
    slug: "samsung-6-cashback-gadgets",
    title: "6% Cashback on Gadgets",
    description: "Buy Samsung phones, TVs and appliances and earn instant cashback. Valid on Samsung.com.",
    href: "/stores?brand=samsung",
    affiliateLink: "https://www.samsung.com/in",
    steps: [
      "Visit Samsung.com/in and log in to your account.",
      "Choose a phone, TV or any appliance.",
      "Add the product to your cart and proceed to checkout.",
      "Apply code 'SAM6BACK' at the payment page.",
      "6% cashback will be credited within 7 working days!",
    ],
  },
];
